[build]
  command = "npm run build"
  publish = "dist"

# DUPLICATE CONTENT FIXES - 301 Redirects to Canonical URLs

# City + Service combinations → Main Service Pages
[[redirects]]
  from = "/mumbai/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/bangalore/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/chennai/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/delhi/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/hyderabad/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/pune/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/kolkata/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/ahmedabad/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/surat/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/jaipur/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

# AI Automation redirects
[[redirects]]
  from = "/mumbai/ai-automation/"
  to = "/services/ai-automation/"
  status = 301

[[redirects]]
  from = "/bangalore/ai-automation/"
  to = "/services/ai-automation/"
  status = 301

[[redirects]]
  from = "/chennai/ai-automation/"
  to = "/services/ai-automation/"
  status = 301

[[redirects]]
  from = "/delhi/ai-automation/"
  to = "/services/ai-automation/"
  status = 301

[[redirects]]
  from = "/hyderabad/ai-automation/"
  to = "/services/ai-automation/"
  status = 301

# Business Automation redirects
[[redirects]]
  from = "/mumbai/business-automation/"
  to = "/services/business-automation/"
  status = 301

[[redirects]]
  from = "/bangalore/business-automation/"
  to = "/services/business-automation/"
  status = 301

[[redirects]]
  from = "/chennai/business-automation/"
  to = "/services/business-automation/"
  status = 301

[[redirects]]
  from = "/delhi/business-automation/"
  to = "/services/business-automation/"
  status = 301

[[redirects]]
  from = "/hyderabad/business-automation/"
  to = "/services/business-automation/"
  status = 301

# SEO Services redirects
[[redirects]]
  from = "/mumbai/seo-services/"
  to = "/services/seo-services/"
  status = 301

[[redirects]]
  from = "/bangalore/seo-services/"
  to = "/services/seo-services/"
  status = 301

[[redirects]]
  from = "/chennai/seo-services/"
  to = "/services/seo-services/"
  status = 301

[[redirects]]
  from = "/delhi/seo-services/"
  to = "/services/seo-services/"
  status = 301

[[redirects]]
  from = "/hyderabad/seo-services/"
  to = "/services/seo-services/"
  status = 301

# PPC Advertising redirects
[[redirects]]
  from = "/mumbai/ppc-advertising/"
  to = "/services/ppc-advertising/"
  status = 301

[[redirects]]
  from = "/bangalore/ppc-advertising/"
  to = "/services/ppc-advertising/"
  status = 301

[[redirects]]
  from = "/chennai/ppc-advertising/"
  to = "/services/ppc-advertising/"
  status = 301

[[redirects]]
  from = "/delhi/ppc-advertising/"
  to = "/services/ppc-advertising/"
  status = 301

[[redirects]]
  from = "/hyderabad/ppc-advertising/"
  to = "/services/ppc-advertising/"
  status = 301

# Social Media Marketing redirects
[[redirects]]
  from = "/mumbai/social-media-marketing/"
  to = "/services/social-media-marketing/"
  status = 301

[[redirects]]
  from = "/bangalore/social-media-marketing/"
  to = "/services/social-media-marketing/"
  status = 301

[[redirects]]
  from = "/chennai/social-media-marketing/"
  to = "/services/social-media-marketing/"
  status = 301

[[redirects]]
  from = "/delhi/social-media-marketing/"
  to = "/services/social-media-marketing/"
  status = 301

[[redirects]]
  from = "/hyderabad/social-media-marketing/"
  to = "/services/social-media-marketing/"
  status = 301

# Wildcard redirects for all other city-service combinations
[[redirects]]
  from = "/*/digital-marketing/"
  to = "/services/digital-marketing/"
  status = 301

[[redirects]]
  from = "/*/ai-automation/"
  to = "/services/ai-automation/"
  status = 301

[[redirects]]
  from = "/*/business-automation/"
  to = "/services/business-automation/"
  status = 301

[[redirects]]
  from = "/*/seo-services/"
  to = "/services/seo-services/"
  status = 301

[[redirects]]
  from = "/*/ppc-advertising/"
  to = "/services/ppc-advertising/"
  status = 301

[[redirects]]
  from = "/*/social-media-marketing/"
  to = "/services/social-media-marketing/"
  status = 301

# Industry + City + Service combinations → Industry pages
[[redirects]]
  from = "/*/industries/*/digital-marketing/"
  to = "/industries/healthcare/"
  status = 301

[[redirects]]
  from = "/*/industries/*/ai-automation/"
  to = "/industries/healthcare/"
  status = 301

[[redirects]]
  from = "/*/industries/*/business-automation/"
  to = "/industries/healthcare/"
  status = 301

[[redirects]]
  from = "/*/industries/*/seo-services/"
  to = "/industries/healthcare/"
  status = 301

[[redirects]]
  from = "/*/industries/*/ppc-advertising/"
  to = "/industries/healthcare/"
  status = 301

[[redirects]]
  from = "/*/industries/*/social-media-marketing/"
  to = "/industries/healthcare/"
  status = 301

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
